#!/bin/bash
# Set up company folder for tailored resume materials
# Usage: setup-company.sh <company-name>

set -e

RESUME_BASE="/Users/azulee/workspace/private/resume"
TAILORED_DIR="$RESUME_BASE/tailored"

if [[ -z "$1" ]]; then
    echo "Usage: $0 <company-name>"
    echo "Example: $0 acme-corp"
    exit 1
fi

# Normalize company name (lowercase, replace spaces with hyphens)
COMPANY_NAME=$(echo "$1" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')
COMPANY_DIR="$TAILORED_DIR/$COMPANY_NAME"

if [[ -d "$COMPANY_DIR" ]]; then
    echo "WARNING: Directory already exists: $COMPANY_DIR"
    echo "Existing files:"
    ls -la "$COMPANY_DIR"
    exit 0
fi

# Create directory
mkdir -p "$COMPANY_DIR"

echo "=== Company Folder Created ==="
echo "Path: $COMPANY_DIR"
echo ""
echo "Expected files:"
echo "  - job-description.md  (save JD here first)"
echo "  - resume.md           (tailored resume)"
echo "  - cover-letter.md     (tailored cover letter)"
echo "  - resume.pdf          (generated by convert-to-pdf.sh)"
echo "  - cover-letter.pdf    (generated by convert-to-pdf.sh)"
